apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $files := .Files }}
  {{- range $path, $bytes := $files.Glob "**.toml" }}
  {{ $path }}: |-
    {{ $files.Get $path | b64enc }}
  {{- end }}
  salad: {{ .Values.global.salad }}
  labels: 
    {{- include "mychart.app" . | nindent 4 }}
  toppings: |-
    {{- range .Files.Lines "toppings.txt" }}
    {{ . }}
    {{- end }}
